name: RepShops

options:
  developmentLanguage: ja
  deploymentTarget:
    iOS: 15.2
  xcodeVersion: "13.2.1"

targets:
  RepShops:
    type: application
    platform: iOS
    sources:
      - RepShops
    info:
      path: RepShops/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    entitlements:
      path: RepShops/RepShops.entitlements
      properties:
        com.apple.security.application-groups: group.com.app
  RepShopsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - RepShopsTests
  RepShopsUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - RepShopsUITests